### ISSUE TITLE
Bulk Uploader Issue - ASAP

### ISSUE THREAD

**Issue by anais-enclavewrx** [jn-devops/rli-bagisto#126]
After merging the latest pull requests, it appears that the bulk uploader feature is malfunctioning

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/f7d7b4ab-b32d-4a03-9652-bb761609aace)

**Comment by VikassWebkul214254** [comment]
![Screenshot from 2024-06-10 11-03-56](https://github.com/jn-devops/rli-bagisto/assets/107629725/fcfcb7df-2d61-432f-8624-7ba53661ac4f)


@anais-enclavewrx 
We have not found any issue. did you changed any file.....

**Comment by anais-enclavewrx** [comment]
hi this is our latest bulk uploader, but we can't see the updated and additional products on our site. 
[bulk_uploader (5).xlsx](https://github.com/user-attachments/files/15758578/bulk_uploader.5.xlsx)

**Comment by VikassWebkul214254** [comment]
ok, We are checking this issue. and update you soon.

**Comment by anais-enclavewrx** [comment]
thank you!

**Comment by VikassWebkul214254** [comment]
> After merging the latest pull requests, it appears that the bulk uploader feature is malfunctioning
> 
> ![image](https://private-user-images.githubusercontent.com/122261359/337968678-f7d7b4ab-b32d-4a03-9652-bb761609aace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTE2NTcsIm5iZiI6MTcxODAxMTM1NywicGF0aCI6Ii8xMjIyNjEzNTkvMzM3OTY4Njc4LWY3ZDdiNGFiLWIzMmQtNGEwMy05NjUyLWJiNzYxNjA5YWFjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwOTIyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzkxMDUzMWY3YTRjYzllOTU2MjE3OTYxYmY2MDFmMzkyODZlNGIwNDExYjRmMWM5YjViYWRmNjQzOTMwN2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BZLHbKwsT1xT8W-AvRWKKOyTpbnTutkkfrmTEbynE-4)

We missed to added Vite config in bagisto-vite file. now added. Please merge above PR.

**Comment by VikassWebkul214254** [comment]
Hello,

Also I have checked. Laravel job is not run automatically on server. i had try it by manual and found job is start and bulk upload work properly. you have to check in attached.
(Job.png)

=======================================
I had already informed you for laravel job over github and Task. (Please check task1.png)

https://github.com/jn-devops/rli-bagisto/issues/117#issuecomment-2146679582
=======================================

We used Laravel Job for bulk upload because we fetch image via cdn and it take to much time and after image will not upload completely because of execution time.

So for this issue we use laravel Job. laravel job will work in background. So first we need to configure supervisor on server because supervisor will help to run laravel jobs on server.
  
For More Details: https://laravel.com/docs/11.x/queues#supervisor-configuration

Thanks & Regards
Vikas Vishwakarma
![Job](https://github.com/jn-devops/rli-bagisto/assets/107629725/55f44137-d12c-4944-a534-3792a1088aea)
![task1](https://github.com/jn-devops/rli-bagisto/assets/107629725/b9194ba3-e236-4832-b95c-cdec4a4f17bc)

**Comment by anais-enclavewrx** [comment]
Please advise us on which connection and queue we should use; we're currently using REDIS.
![Uploading laravel forge queue.jpg…]()

**Comment by anais-enclavewrx** [comment]
Hi! please check error below. Thank you

![image](https://github.com/jn-devops/rli-bagisto/assets/122261359/57a5945e-8dbc-47fc-9b67-a78dcb8a0cfe)

**Comment by VikassWebkul214254** [comment]
@all Issue Fixed now site is working.
